import { useAppStore } from '../../store/useAppStore';

export function SheetView() {
    const { song } = useAppStore();

    if (!song) return null;

    const renderContent = (content: string, type: 'chord' | 'tab') => {
        if (type === 'tab') {
            return <pre className="font-mono text-[13px] leading-tight overflow-x-auto p-5 bg-gray-50/80 rounded-xl border border-gray-100 text-gray-800 shadow-inner">{content}</pre>;
        }

        // Chord mode: Highlight bracketed chords
        const lines = content.split('\n');
        return (
            <div className="space-y-1.5 font-sans text-[15px] text-gray-700">
                {lines.map((line, idx) => {
                    if (!line.trim()) return <div key={idx} className="h-4" />; // Empty lines

                    const parts = line.split(/\[(.*?)\]/g);
                    return (
                        <div key={idx} className="leading-relaxed tracking-wide">
                            {parts.map((part, i) =>
                                i % 2 === 1
                                    ? <span key={i} className="text-indigo-800 font-bold bg-indigo-50/80 px-1.5 py-0.5 rounded mx-0.5 inline-block border border-indigo-100 shadow-sm transform -translate-y-px">{part}</span>
                                    : <span key={i}>{part}</span>
                            )}
                        </div>
                    );
                })}
            </div>
        );
    };

    return (
        <div className="w-full max-w-[850px] bg-white shadow-2xl rounded-sm min-h-[1100px] p-12 lg:p-16 border border-gray-200 printable-sheet flex flex-col relative" id="sheet-container">

            {/* Document Header */}
            <header className="border-b-2 border-gray-100 pb-8 mb-8 flex flex-col">
                <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 mb-2">{song.metadata.name}</h1>
                <div className="flex justify-between items-end">
                    <h2 className="text-xl font-medium text-gray-600 italic">By {song.metadata.artist}</h2>

                    <div className="flex gap-4 text-sm font-semibold text-gray-500 uppercase tracking-widest bg-gray-50 px-4 py-2 rounded-lg border border-gray-100">
                        <div>Key: <span className="text-gray-900 ml-1">{song.metadata.originalKey}</span></div>
                        <div className="w-px h-4 bg-gray-300 self-center"></div>
                        <div>BPM: <span className="text-gray-900 ml-1">{song.bpm}</span></div>
                    </div>
                </div>
            </header>

            {/* Chord Used Section */}
            {song.chordsUsed && song.chordsUsed.length > 0 && (
                <div className="mb-10 bg-gray-50/50 p-6 rounded-xl border border-gray-100">
                    <h3 className="text-xs font-bold uppercase tracking-widest text-indigo-400 mb-4 flex items-center gap-2">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" /></svg>
                        Chords Dictionary
                    </h3>
                    <div className="flex gap-4 flex-wrap">
                        {song.chordsUsed.map(chord => (
                            <div key={chord} className="min-w-16 px-4 h-16 bg-white border border-gray-200 rounded-lg shadow-sm flex items-center justify-center font-bold text-gray-800 text-lg hover:border-indigo-300 transition-colors">
                                {chord}
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Content Area */}
            <div className="flex-1 space-y-10">
                {song.sections.map((section, index) => (
                    <section key={index} className="song-section">
                        <h4 className="text-sm font-bold uppercase tracking-widest text-gray-400 mb-3 ml-2 border-l-4 border-indigo-200 pl-3">
                            {section.name}
                        </h4>
                        <div className="pl-4">
                            {renderContent(section.content, song.type)}
                        </div>
                    </section>
                ))}
            </div>

            {/* Footer stamp */}
            <div className="mt-16 pt-8 border-t border-gray-100 text-center text-xs text-gray-400 font-medium">
                Generated by DeepSeek AI Guitar Sheet Generator • {new Date(song.metadata.transcribedAt).toLocaleDateString()}
            </div>
        </div>
    );
}
